{ self, ... }: {
  imports = [
    "${self}/user/pkg/alsa.nix"
    "${self}/user/pkg/anki.nix"
    "${self}/user/pkg/appimage.nix"
    "${self}/user/pkg/content.nix"
    "${self}/user/pkg/bottles.nix"
    "${self}/user/pkg/brave.nix"
    "${self}/user/pkg/btop.nix"
    "${self}/user/pkg/colorpicker.nix"
    "${self}/user/pkg/docker.nix"
    "${self}/user/pkg/fastfetch.nix"
    "${self}/user/pkg/findex.nix"
    "${self}/user/pkg/firefox"
    "${self}/user/pkg/font.nix"
    "${self}/user/pkg/games.nix"
    "${self}/user/pkg/geogebra.nix"
    "${self}/user/pkg/gh.nix"
    "${self}/user/pkg/ghostty.nix"
    "${self}/user/pkg/git.nix"
    "${self}/user/pkg/gnome.nix"
    "${self}/user/pkg/gradience.nix"
    "${self}/user/pkg/heif.nix"
    "${self}/user/pkg/helix"
    "${self}/user/pkg/hid.nix"
    "${self}/user/pkg/intellij.nix"
    "${self}/user/pkg/javascript.nix"
    "${self}/user/pkg/kdeconnect.nix"
    "${self}/user/pkg/kdenlive.nix"
    "${self}/user/pkg/kicad.nix"
    "${self}/user/pkg/krita.nix"
    "${self}/user/pkg/minecraft.nix"
    "${self}/user/pkg/obs.nix"
    "${self}/user/pkg/obsidian.nix"
    "${self}/user/pkg/planify.nix"
    "${self}/user/pkg/rstudio.nix"
    "${self}/user/pkg/sass.nix"
    "${self}/user/pkg/screenshot.nix"
    "${self}/user/pkg/siril.nix"
    "${self}/user/pkg/swww.nix"
    "${self}/user/pkg/thunderbird.nix"
    "${self}/user/pkg/tree.nix"
    "${self}/user/pkg/typescript.nix"
    "${self}/user/pkg/via.nix"
    "${self}/user/pkg/wezterm"
    "${self}/user/pkg/yazi.nix"
  ];

  xdg.mimeApps = {
    enable = true;
    defaultApplications = { "inode/directory" = "org.gnome.Nautilus.desktop"; };
  };
}
