{ pkgs, unstable, ... }: {
  home.packages = with pkgs; [
    gnome.gnome-calculator
    errands
    fragments
    gnome.nautilus
    emblem
    dialect
    impression
    amberol
    authenticator
    video-trimmer
    wike
    unstable.showtime
    ffmpeg
    gst-plugins-base
    gst-plugins-good
    gst-plugins-ugly
    gstreamer-libav
    unstable.decibels
    denaro
    parabolic
    unstable.rnote
    snapshot
    gnome.gnome-clocks
    pika-backup
    # unstable.gnome-weather
    mousam
    foliate
    apostrophe
    alpaca
    easyeffects
    resources
    impression
    hieroglyphic
    gnome.gnome-calendar
    gnome-maps
    loupe
    hyprnome
    exhibit
  ];
}
