{ pkgs, unstable, ... }: {
  home.packages = with pkgs; [
    gnome-calculator
    errands
    fragments
    gnome.nautilus
    emblem
    dialect
    impression
    amberol
    unstable.termusic
    authenticator
    video-trimmer
    wike
    unstable.showtime
    ffmpeg
    gst
    gst_all_1.gst-libav
    gst_all_1.gstreamer
    unstable.decibels
    denaro
    parabolic
    unstable.rnote
    snapshot
    gnome.gnome-clocks
    pika-backup
    # unstable.gnome-weather
    mousam
    foliate
    apostrophe
    alpaca
    easyeffects
    resources
    impression
    hieroglyphic
    gnome.gnome-calendar
    gnome-maps
    loupe
    hyprnome
    exhibit
    gnome-solanum
    bluetui
  ];
}
